srr_sample_file: '/Users/mcgaugheyd/git/scEiaD_quant/sample_mini.tsv'
ref_file: '/Users/mcgaugheyd/git/scEiaD_quant/reference_table.tsv'
git_dir: '/Users/mcgaugheyd/git/scEiaD_quant/' 
working_dir: '/data/mcgaugheyd/projects/nei/mcgaughey/scEiaD_2024_01/'
config_abspath: '/data/mcgaugheyd/projects/nei/mcgaughey/scEiaD_2024_01/config/config.yaml'
fastq_path: '/data/OGVFB_BG/scEiaD'
quant_path: '/data/OGVFB_BG/scEiaD/2024_01_21'
